apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-1akp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0034-tenant/tkrw-pr712-0075-0034-app/devfile-sample-1akp@sha256:012ed362ed7fd9e145ab78222f36e3a28b0b1be4358df0b7da96149cf2c12dfc
        name: my-nodejs
        resources: {}
status: {}
